### ISSUE TITLE
CSS of Progress Bar messes with other "position: fixed"-elements on mobile safari

### ISSUE THREAD

**Issue by marczking** [rails/turbolinks#579]
When testing my site on `iPhone 3GS` with iOS 6 and Safari 6 I was having following issue:

#### issue

As soon as an other element on my page had a `position: fixed` my whole screen turned to the color of the progress bar (blue). As soon as I removed `turbolinks-progress-bar` from my `html`-tag all worked again.

So the CSS of turbolinks:pseudo-element was conflicting with my other fixed-element. I *think* this might be a bug of Safari...

#### example

I've put together a minimal example using only CSS, as the issue is not with the JS:

Working example: Here you see how it should look
http://codepen.io/marczking/full/BNOqVZ/

And here you encounter the issue:
http://s.codepen.io/marczking/debug/BNOqVZ?
(be sure to test with iOS 6 Safari or similar)

#### my solution
I just disabled the progressBar for mobile devices. This is no full solution, but at least the site does not break on those devices.

As I mentioned before, this might be a Safari bug, but I am posting this here, as it is caused when using turbolinks.

#### code for reference
```html
<html>
  <div id="fixed"></div>
</html>
```
```css
html::before {
  content: '';
  position: fixed;
  top: 0;
  left: 0;
  z-index: 2000;
  background-color: #0076ff;
  height: 3px;
  opacity: 0.99;
  width: 30%;
  transition: width 300ms ease-out, opacity 150ms ease-in;
  transform: translate3d(0,0,0);
}

#fixed {
  position: fixed;
  top: 0;
}
```
